---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  vars_files:
   - ../creds/credentials.yaml

  tasks:s
  - name: Create a JIRA issue
  uri:
    url: https://20.0.58.197:8443/mgmt/shared/appsvcs/declare
    user: your_username
    password: your_pass
    method: POST
    body: "{{ lookup('file','as3-declaration.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: json
    validate_certs: no
  ...
